core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

app_name = 'core'

urlpatterns = [
    path('index/', views.index, name='index'),

    path('recipes/', views.RecipesList.as_view(), name='recipes'),
    path('recipes/<int:pk>', views.RecipeDetail.as_view(), name='recipe'),
    path('recipes/components/<int:pk>', views.ComponentDetail.as_view(), name='recipe_component'),
    path('recipes/tools/<int:pk>', views.ToolDetail.as_view(), name='recipe_tool'),
    path('recipe_create', views.RecipeCreate.as_view(), name='recipe_create'),
    path('recipe_update/<int:pk>', views.UpdateRecipe.as_view(), name='recipe_update'),
    path('recipe_delete/<int:pk>', views.DeleteRecipe.as_view(), name='recipe_delete'),

    path('components/', views.ComponentsList.as_view(), name='components'),
    path('components/<int:pk>', views.ComponentDetail.as_view(), name='component'),
    path('component_create', views.ComponentCreate.as_view(), name='component_create'),
    path('component_update/<int:pk>', views.UpdateComponent.as_view(), name='component_update'),
    path('component_delete/<int:pk>', views.DeleteComponent.as_view(), name='component_delete'),

    path('tools/', views.ToolsList.as_view(), name='tools'),
    path('tools/<int:pk>', views.ToolDetail.as_view(), name='tool'),
    path('tool_create', views.ToolCreate.as_view(), name='tool_create'),
    path('tool_update/<int:pk>', views.UpdateTool.as_view(), name='tool_update'),
    path('tool_delete/<int:pk>', views.DeleteTool.as_view(), name='tool_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
]

core/models.py
from django.db import models


class User(models.Model):
    name = models.CharField('Имя', max_length=255)
    dc = models.DateTimeField(auto_now_add=True)


class UserId(models.Model):
    number = models.CharField(max_length=255, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='userid')


class Component(models.Model):
    name = models.CharField('Название', max_length=255)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    count = models.FloatField('Количество', null=True, blank=True)
    unit = models.CharField('Единица измрения', max_length=50, null=True)
    price = models.FloatField('Цена', null=True)
    cost = models.FloatField('Стоимость', null=True, blank=True)
    parent = models.BooleanField(default=True)
    parent_id = models.IntegerField(null=True, blank=True)


class Tool(models.Model):
    name = models.CharField('Название', max_length=255)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    cost = models.FloatField('Стоимость', null=True)
    usage = models.IntegerField('Срок использования', null=True)
    time = models.IntegerField('Время применения', null=True, default=0)
    depreciation = models.FloatField('Амортизация', null=True)
    parent = models.BooleanField(default=True)
    parent_id = models.IntegerField(null=True)


class Recipe(models.Model):
    name = models.CharField('Название', max_length=255)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    description = models.TextField('Описание', null=True)
    components = models.ManyToManyField(Component, null=True, verbose_name='Ингредиенты', related_name='recipe')
    tools = models.ManyToManyField(Tool, null=True, verbose_name='Инструменты', related_name='recipe')
    count = models.IntegerField('Выход', default=1)
    primecost = models.FloatField('Себестоимость', null=True)
    parent = models.BooleanField(default=True)
    parent_id = models.IntegerField(null=True, default=0)

core/forms.py
from django import forms
from core import models


# region SearchForms
class RecipeSearch(forms.Form):

    name = forms.CharField(label='Поиск рецепта', required=False,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))


class ComponentSearch(forms.Form):
    name = forms.CharField(label='Поиск ингредиента', required=False,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))


class ToolSearch(forms.Form):
    name = forms.CharField(label='Поиск инструмента', required=False,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
# endregion


# region CreateForms
class CreateComponent(forms.ModelForm):
    price = forms.FloatField(label="Цена", min_value=0.1)

    class Meta:
        model = models.Component
        fields = ('name', 'unit', 'price',)

    def clean_name(self):
        name = self.cleaned_data['name']
        if name.isdigit:
            raise forms.ValidationError('Имя не может быть числом!')
        return name

    def clean_unit(self):
        name = self.cleaned_data['name']
        if name.isdigit:
            raise forms.ValidationError('Введите буквенную единицу измерения!')
        return name


class CreateTool(forms.ModelForm):
    name = forms.CharField(label='Название', min_length=2)
    cost = forms.FloatField(label="Стоимость", min_value=1)
    usage = forms.IntegerField(label="Срок использования (месяцев)", min_value=1)

    class Meta:
        model = models.Tool
        fields = ('name', 'cost', 'usage',)

    def clean_name(self):
        name = self.cleaned_data['name']
        if name.isdigit:
            raise forms.ValidationError('Название не может быть числом!')
        return name

'''
class ComponentMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return f'{obj.name} (Цена: {obj.price})'


class ToolMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return f'{obj.name} (Стоимость: {obj.cost}, срок использования: {obj.usage})'
'''


class CreateRecipe(forms.ModelForm):
    # components = ComponentMultipleChoiceField(models.Component.objects.filter(parent=True).order_by('name'))
    # tools = ToolMultipleChoiceField(models.Tool.objects.filter(parent=True).order_by('name'))
    name = forms.CharField(label='Название', min_length=2)
    description = forms.CharField(label='Описание', widget=forms.Textarea, required=False)

    class Meta:
        model = models.Recipe
        fields = ('name', 'description', )

    def clean_name(self):
        name = self.cleaned_data['name']
        if name.isdigit:
            raise forms.ValidationError('Название не может быть числом!')
        return name
# endregion

core/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import Template, Context
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from core import models, forms
from core.datatools import recipe_datatools


class TitleMixin:
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_title()
        return context


def index(request):
    user = request.user.username
    if user != 'admin':
        html = "<html> <head> <title>Главная страница </title>" \
               "<style>.fade-effect{transition: color 0.5s; color:#000000} .fade-effect:hover{color:#999999}</style></head>" \
               "<body> <h1 class='fade-effect'> Привет, анон </h1> </body> </html>"
    return HttpResponse(html)


# region ListViews
class RecipesList(TitleMixin, ListView):
    model = models.Recipe
    template_name = 'core/recipes_list.html'
    context_object_name = 'recipes'
    title = 'База рецептов'
    form = forms.RecipeSearch()

    def get_queryset(self):
        name = self.request.GET.get('name')
        qs = models.Recipe.objects.all()
        for i in qs:
            recipe_datatools.calculate_primecost(i)

        if name:
            return qs.filter(name__icontains=name)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = forms.RecipeSearch(self.request.GET or None)
        context['request_name'] = self.request.GET.get('name')
        return context


class ComponentsList(TitleMixin, ListView):
    model = models.Component
    template_name = 'core/components_list.html'
    context_object_name = 'components'
    title = 'База ингредиентов'

    def get_queryset(self):
        name = self.request.GET.get('name')
        parent_components = list(filter(lambda x: x.parent, models.Component.objects.all()))
        qs = parent_components
        print(qs)
        if name:
            return qs.filter(name__icontains=name)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = forms.ComponentSearch(self.request.GET or None)
        context['request'] = self.request.GET.get('name')
        return context


class ToolsList(TitleMixin, ListView):
    model = models.Tool
    template_name = 'core/tools_list.html'
    context_object_name = 'tools'
    title = 'База инструментов'

    def get_queryset(self):
        name = self.request.GET.get('name')
        parent_tools = filter(lambda x: x.parent, models.Tool.objects.all())
        qs = parent_tools
        if name:
            return qs.filter(name__icontains=name)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = forms.ToolSearch(self.request.GET or None)
        context['request'] = self.request.GET.get('name')
        return context
# endregion


# region DetailViews
class RecipeDetail(DetailView):
    model = models.Recipe
    template_name = 'core/recipe_detail.html'
    context_object_name = 'recipe'

    def get_context_data(self, **kwargs):
        recipe = models.Recipe.objects.get(id=self.kwargs['pk'])
        recipe_datatools.calculate_primecost(recipe)

        context = super().get_context_data(**kwargs)
        context['title'] = f"Рецепт «{recipe.name}»"
        context['recipe'] = recipe
        return context


class ComponentDetail(DetailView):
    model = models.Component
    template_name = 'core/component_detail.html'
    context_object_name = 'recipe_component'

    def get_context_data(self, **kwargs):
        component = self.model.objects.get(id=self.kwargs['pk'])
        context = super().get_context_data(**kwargs)
        context['title'] = f"Ингредиент «{component.name}»"
        context['param1'] = ['Цена', component.price]
        if component.count:
            context['param2'] = ['Количество (у.е.)', component.count]
        return context


class ToolDetail(DetailView):
    model = models.Tool
    template_name = 'core/component_detail.html'
    context_object_name = 'recipe_tool'

    def get_context_data(self, **kwargs):
        tool = self.model.objects.get(id=self.kwargs['pk'])
        context = super().get_context_data(**kwargs)
        context['title'] = f"Инструмент «{tool.name}»"
        context['param1'] = ['Цена', tool.cost]
        if tool.usage:
            context['param2'] = ['Срок использования (мес.)', tool.usage]
        return context
# endregion


# region CreateViews
class ComponentCreate(TitleMixin, CreateView):
    title = 'Создание ингредиента'
    model = models.Component
    template_name = 'core/create_component.html'
    form_class = forms.CreateComponent
    success_url = reverse_lazy('core:components')


class ToolCreate(TitleMixin, CreateView):
    title = 'Создание инструмента'
    model = models.Tool
    template_name = 'core/create_tool.html'
    form_class = forms.CreateTool
    success_url = reverse_lazy('core:tools')


class RecipeCreate(TitleMixin, CreateView):
    title = 'Создание рецепта'
    model = models.Recipe
    template_name = 'core/create_recipe.html'
    form_class = forms.CreateRecipe
    success_url = reverse_lazy('core:recipes')

    '''
    def get_success_url(self):
        return reverse('core:recipes', args=(int(self.object.pk),))
    '''


# region UpdateViews
class UpdateComponent(UpdateView):
    model = models.Component
    template_name = 'core/update_component.html'
    form_class = forms.CreateComponent
    success_url = reverse_lazy('core:components')


class UpdateTool(UpdateView):
    model = models.Tool
    template_name = 'core/update_tool.html'
    form_class = forms.CreateTool
    success_url = reverse_lazy('core:tools')


class UpdateRecipe(UpdateView):
    model = models.Recipe
    template_name = 'core/update_recipe.html'
    form_class = forms.CreateRecipe
    success_url = reverse_lazy('core:recipes')

# endregion


# region DeleteViews

class DeleteComponent(DeleteView):
    model = models.Component
    template_name = 'core/delete_component.html'
    success_url = reverse_lazy('core:components')


class DeleteTool(DeleteView):
    model = models.Tool
    template_name = 'core/delete_tool.html'
    success_url = reverse_lazy('core:tools')


class DeleteRecipe(DeleteView):
    model = models.Recipe
    template_name = 'core/delete_recipe.html'
    success_url = reverse_lazy('core:recipes')

# endregion

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

  <style>
      @import "bootstrap";

      $color: #2e3f7f;
      .btn-primary:{
        background-color: #2e3f7f;
        color: white;
      }

      .container{
        height: 125%
      }
    </style>


</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <img src="{% static 'images/LogoCircle.png' %}" height="50px" width="50px">
        <a class="navbar-brand" href="{% url 'core:recipes' %}" style="color:#2e3f7f">RecipeCostBase</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'core:recipes' %}">Рецепты</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'core:components' %}">Ингредиенты</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'core:tools' %}">Инструменты</a>
            </li>
          </ul>

          {% if search_form %}
          <form class="d-flex" method="GET">
            {{ search_form }}
            <button class="btn btn-primary" type="submit" style="background-color: #2e3f7f; color: white;">
              поиск
            </button>
          </form>
          {% endif %}

        </div>
      </div>
  </nav>
  <br>
  <div>
    {% block content %}

    {% endblock %}
  </div>
  <br>
  <footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Следите за обновлениями в соц. сетях:</span>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-5 mx-auto mb-1">
            <!-- Content -->

            <h6 class="text-uppercase fw-bold mb-4" style="color: #2e3f7f">
              <img src="{% static 'images/LogoCircle.png' %}" height="50px" width="50px">
              RecipeCostBase
            </h6>
            <p>
              База себестоимости рецептов. Создавайте и делитесь рецептами,
              рассчитывайте себестоимость ваших изделий, учитывая необходимые компоненты, а также амортизацию инструментов!
            </p>
          </div>
          <!-- Grid column -->


          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-5 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4" style="color: #2e3f7f">Контакты</h6>
            <p><a href="mailto:ksigames4@gmail.com">ksigames4@gmail.com</a></p>
            <p><a href="http://recipecost.tilda.ws/">Сайт</a></p>
            <p><a href="http://t.me/primecost_bot">Telegram бот</a></p>
            <p><a href="http://t.me/primecostbot_reviews">Telegram канал</a></p>
            <p><a href="http://instagram.com/recipecostbot">Instagram</a></p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: #2e3f7f; color: white;">
      © 2023 Copyright:
      <a class="text-reset fw-bold" href="http://recipecost.tilda.ws/">RecipeCostBot</a>
    </div>
    <!-- Copyright -->
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/component_detail.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <h3>{{ param1.0 }}: {{ param1.1 }}</h3>
    {% if param2 %}
        <br>
        <h3>{{ param2.0 }}: {{ param2.1 }}</h3>
    {% endif %}
    <br>
    <a href="{{request.META.HTTP_REFERER}}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">
        <b>Назад</b>
    </a>
</div>
{% endblock %}

core/templates/core/components_list.html
{% extends "core/base.html" %}
{% block content %}
    <div class="container">
        <h1>{{ title }}</h1>
        <br>
        <a href="{% url 'core:component_create' %}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">
            <b>Создать</b>
        </a>
        <br>
        {% if components %}
        <table class="table table-bordered">
          <thead>
            <tr style="background-color: #2e3f7f; color: white;">
                <th>Название</th>
                <th>Цена</th>
                <th>Создатель</th>
            </tr>
          </thead>
          <tbody>
          {% for component in components %}
            <tr>
                <td>
                    <a href="{% url 'core:component' component.pk %}">{{ component.name }}</a>
                    {% if request.user.superuser or request.user.id == component.owner.id %}
                    (<a href="{% url 'core:component_update' component.pk %}">редактировать</a>) |
                    (<a href="{% url 'core:component_delete' component.pk %}">удалить</a>)
                    {% endif %}

                </td>
                <td>{{ component.price }} / {{ component.unit }}</td>
                {% if recipe.owner %}
                <td>{{ component.owner.name }} ({{ component.owner.id }})</td>
                {% else %}
                <td>Гость</td>
                {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
        {% elif request_name %}
        <p>Ингредиентов по запросу <b>«{{ request_name }}»</b> не найдено.</p>
        {% else %}
        <p>Ингредиентов не найдено.</p>
        {% endif %}
    </div>
{% endblock %}

core/templates/core/create_component.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <br>
    <form action="{% url 'core:component_create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Создать</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Назад</a>
    </form>
    <br>

</div>



{% endblock %}

core/templates/core/create_recipe.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <form action="{% url 'core:recipe_create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Создать</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Назад</a>
    </form>
    <br>

</div>



{% endblock %}

core/templates/core/create_tool.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <form action="{% url 'core:tool_create' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Создать</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Назад</a>
    </form>
    <br>

</div>



{% endblock %}

core/templates/core/delete_component.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>Удалить ингредиент «{{ component.name }}»?</h1>
    <br>
    <form action="{% url 'core:component_delete' component.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Удалить</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Назад</a>
    </form>
</div>

{% endblock %}

core/templates/core/delete_recipe.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>Удалить рецепт «{{ recipe.name }}»?</h1>
    <br>
    <form action="{% url 'core:recipe_delete' recipe.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Удалить</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Назад</a>
    </form>
</div>

{% endblock %}

core/templates/core/delete_tool.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>Удалить инструмент «{{ component.name }}»?</h1>
    <br>
    <form action="{% url 'core:tool_delete' tool.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Удалить</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Назад</a>
    </form>
</div>

{% endblock %}

core/templates/core/recipes_list.html
{% extends "core/base.html" %}
{% block content %}
    <div class="container">
        <h1>{{ title }}</h1>
        <br>
        <a href="{% url 'core:recipe_create' %}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">
            <b>Создать</b>
        </a>
        <br>
        {% if recipes %}
        <table class="table table-bordered">
          <thead>
            <tr style="background-color: #2e3f7f; color: white;">
                <th>Название</th>
                <th>Описание</th>
                <th>Выход</th>
                <th>Себестоимость</th>
                <th>Создатель</th>
            </tr>
          </thead>
          <tbody>
          {% for recipe in recipes %}
            <tr>
                <td>
                    <a href="{% url 'core:recipe' recipe.pk %}">{{ recipe.name }}</a>
                    {% if request.user.superuser or request.user.id == component.owner.id %}
                    (<a href="{% url 'core:recipe_update' recipe.pk %}">редактировать</a>) |
                    (<a href="{% url 'core:recipe_delete' recipe.pk %}">удалить</a>)
                    {% endif %}
                </td>

                {% if recipe.description %}
                <td>{{ recipe.description }}</td>
                {% else %}
                <td>-</td>
                {% endif %}
                <td>{{ recipe.count }}</td>
                <td>{{ recipe.primecost }}</td>
                {% if recipe.owner %}
                <td>{{ recipe.owner.name }} ({{ recipe.owner.id }})</td>
                {% else %}
                <td>Гость</td>
                {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
        {% elif request_name %}
        <p>Рецептов по запросу <b>«{{ request_name }}»</b> не найдено.</p>
        {% else %}
        <p>Рецептов не найдено.</p>
        {% endif %}
    </div>
  {% endblock %}

core/templates/core/tools_list.html
{% extends "core/base.html" %}
{% block content %}
    <div class="container">
        <h1>{{ title }}</h1>
        <br>
        <a href="{% url 'core:tool_create' %}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">
            <b>Создать</b>
        </a>
        <br>
        {% if tools %}
        <table class="table table-bordered">
          <thead>
            <tr style="background-color: #2e3f7f; color: white;">
                <th>Название</th>
                <th>Стоимость</th>
                <th>Срок использования</th>
                <th>Создатель</th>
            </tr>
          </thead>
          <tbody>
          {% for tool in tools %}
            <tr>
                <td>
                    <a href="{% url 'core:tool' tool.pk %}">{{ tool.name }}</a>
                    {% if request.user.superuser or request.user.id == tool.owner.id %}
                    (<a href="{% url 'core:tool_update' tool.pk %}">редактировать</a>) |
                    (<a href="{% url 'core:tool_delete' tool.pk %}">удалить</a>)
                    {% endif %}
                </td>
                <td>{{ tool.cost }}</td>
                <td>{{ tool.usage }}</td>
                {% if recipe.owner %}
                <td>{{ recipe.owner.name }} ({{ recipe.owner.id }})</td>
                {% else %}
                <td>Гость</td>
                {% endif %}
            </tr>
          {% endfor %}
          </tbody>
        </table>
        {% elif request_name %}
        <p>Инструментов по запросу <b>«{{ request_name }}»</b> не найдено.</p>
        {% else %}
        <p>Инструментов не найдено.</p>
        {% endif %}
    </div>
{% endblock %}

core/templates/core/update_component.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>Редактирование ингредиента «{{ component.name }}»</h1>
    <br>
    <form action="{% url 'core:component_update' component.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Сохранить</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Назад</a>
    </form>
    <br>
</div>

{% endblock %}

core/templates/core/update_recipe.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>Редактирование рецепта «{{ tool.name }}»</h1>
    <br>
    <form action="{% url 'core:recipe_update' recipe.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Сохранить</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">
        <b>Назад</b>
    </a>
    </form>
    <br>

</div>

{% endblock %}

core/templates/core/update_tool.html
{% extends "core/base.html" %}
{% block content %}
<div class="container">
    <h1>Редактирование инструмента «{{ tool.name }}»</h1>
    <br>
    <form action="{% url 'core:tool_update' tool.pk %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Сохранить</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary" style="background-color: #2e3f7f; color: white;">Назад</a>
    </form>
    <br>

</div>

{% endblock %}